### ISSUE TITLE
Admin interface - Channel Info

### ISSUE THREAD

**Issue by Valenteeena** [zurichat/zc_plugin_channels#225]

**Comment by mrkendrick** [comment]
Component Title: Admin Interface Channel Info (Details)
Description: To show the channel details to the admin and other configuration
Live Testing Link: https://channels.zuri.chat/admin
Slack Name: Charles
PR Link: https://github.com/zurichat/zc_plugin_channels/pull/260
![Screenshot_20210903-121623~2](https://user-images.githubusercontent.com/48606363/131997117-9f4f10d2-b4b4-4024-bc8d-1e053559d676.png)
![Screenshot_20210903-121751~2](https://user-images.githubusercontent.com/48606363/131997250-1ee0b1fe-ee52-4fbc-af91-079cc886710f.png)
