### ISSUE TITLE
New Channel - Message input

### ISSUE THREAD

**Issue by Valenteeena** [zurichat/zc_plugin_channels#232]

**Comment by PhoenixAqua** [comment]
Task completed.
I created the message input section at the bottom of the screen
**Live Link:** https://channels.zuri.chat/create-channel
**Pull Request:** https://github.com/zurichat/zc_plugin_channels/pull/304

**Comment by PhoenixAqua** [comment]
![image](https://user-images.githubusercontent.com/73500258/131999151-8821f994-86f9-4109-aa7a-822c4f161624.png)
