### ISSUE TITLE
Add Member to Channel Component

### ISSUE THREAD

**Issue by Valenteeena** [zurichat/zc_plugin_channels#235]

**Comment by dvlapo** [comment]
I created the add member to channel component 

Live Link: https://channels.zuri.chat/create-channel

Pull Request: #364 
Design Link: https://www.figma.com/file/cgUnQ1il3Y9sEZZXJ6nNi6/Channels-HNG-Task?node-id=17%3A15327
Slack Name: dvlapo

![Screenshot (256)~2](https://user-images.githubusercontent.com/80985036/132021562-ce25ed19-f5a7-40a4-896e-bc65013be2a5.png)

**Comment by dvlapo** [comment]
closes #235
