### ISSUE TITLE
Channels Details & Setting - Channel name Banner

### ISSUE THREAD

**Issue by Valenteeena** [zurichat/zc_plugin_channels#249]

**Comment by odelolajosh** [comment]
This component should
- [x] Show the name of a channel
- [x] Show the number of members in the channel
- [x] Show preview of members profile avatar
- [x] Show an interface to invite members to the channel

Live Link https://channels.zuri.chat/admin

Pull Request #319

**Comment by Abraham-Ogbumah** [comment]
### Channel Detail and Settings Banner

This component the banner for the Channels details and settings page.

### Live Link

The component is live in https://channels.zuri.chat/channel-detail

Other items were worked on by members of the Channel Details and Setings Team

<img width="590" alt="Screenshot 2021-09-05 at 10 04 58" src="https://user-images.githubusercontent.com/23290222/132121570-5ecea8e0-a0a6-4da8-9921-9dcad5c2168e.png">
