### ISSUE TITLE
Channels Details & Setting - About Section

### ISSUE THREAD

**Issue by Valenteeena** [zurichat/zc_plugin_channels#251]

**Comment by Marrockx** [comment]
#### Component Title: Create Channel About Section

- **User Story**: As a User, I  should be able to set the descriptions and topics of a channel


- **Description**: For users to provide details about the channel for other members or potiential members to be aware.

- **Live Testing Link**: https://channels.zuri.chat/

- **Slack Name**: devmariam

- **PR Link**: #

#### How to view Component
Click the Channel Settings icon button on the homepage to view Channel Details and Settings, then see the About Section
![channel-about](https://user-images.githubusercontent.com/32394325/132040789-d4fe0aa2-150e-4d12-8146-615390308be2.png)
![channel-about-1](https://user-images.githubusercontent.com/32394325/132040802-25214615-9129-47e1-8a23-49b164cda579.png)
![channel-about2](https://user-images.githubusercontent.com/32394325/132040814-fbda6865-e34a-4bf0-bd5d-d899048a86f6.png)
