### ISSUE TITLE
Channels Details & Setting - Files List

### ISSUE THREAD

**Issue by Valenteeena** [zurichat/zc_plugin_channels#252]

**Comment by buquio** [comment]
Yes working on this

**Comment by buquio** [comment]
**Description**: As a user on clicking to see any channel info I should be able to also see all files associated with that channel. 

issue link: https://github.com/zurichat/zc_plugin_channels/issues/252

PR issue: 


a screen shot:
![filelist](https://user-images.githubusercontent.com/58447252/132042950-94391188-e910-4f8f-bd40-74b3eecc2876.PNG)
