### ISSUE TITLE
Message Board - Message Cards Component

### ISSUE THREAD

**Issue by Valenteeena** [zurichat/zc_plugin_channels#270]

**Comment by Harithmetic1** [comment]
User Stories:
1. As a user, I should be able to see messages sent to the channel to see who sent it, when it was sent, and what was sent.
2. As a user, I should know when a message has a thread, so I can know the number of replies to a particular message card, the profile pic of some of the users who replied, and the last reply time.

Live Link:  https://channels.zuri.chat/message-board
Link to PR: `[#265](https://github.com/zurichat/zc_plugin_channels/pull/265)`
