### ISSUE TITLE
Message Board - Input Field Component

### ISSUE THREAD

**Issue by Valenteeena** [zurichat/zc_plugin_channels#278]

**Comment by Xtarachiever** [comment]
This channel details should:

- [ ] Show the input box, where users can send information.
- [ ] Show the different options for text formatting.
- [ ] Show the **@ tag** for tagging other users in the channel.
- [ ] Have a button for sending messages to the channel.

**Comment by Xtarachiever** [comment]
[https://channels.zuri.chat/message-board](url)
![Screenshot (296) (1)](https://user-images.githubusercontent.com/63353240/131991294-ea1f2349-850d-4e65-8874-3d5f7771ea12.png)
