### ISSUE TITLE
Message Board - Channel Details Component

### ISSUE THREAD

**Issue by Valenteeena** [zurichat/zc_plugin_channels#279]

**Comment by JulianaSau** [comment]
The channel details component should:
- [ ]Show the channel name

- [ ] Show avatars of a few members of the group

- [ ] Display the number of members in the channel

- [ ] Have a button that allows one to invite/add members to the channel

**Comment by JulianaSau** [comment]
![channel details component](https://user-images.githubusercontent.com/49183775/132012733-04aae971-3b74-4c4b-8746-46d07d6a331c.JPG)
This is a screenshot of the channel details component.
Testing link: https://channels.zuri.chat/message-board
PR link: #275
